package hbi.demo.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.format.annotation.DateTimeFormat;

@ExtensionAttribute(disable=true)
@Table(name = "hbi_demo_bank_branch")
public class DemoBankBranch extends BaseDTO {

     public static final String FIELD_BANK_BRANCH_ID = "bankBranchId";
     public static final String FIELD_BANK_ID = "bankId";
     public static final String FIELD_BRANCH_NAME = "branchName";
     public static final String FIELD_BRANCH_TYPE = "branchType";
     public static final String FIELD_BRANCH_NO = "branchNo";
     public static final String FIELD_SWIFT_CODE = "swiftCode";
     public static final String FIELD_ADDRESS = "address";
     public static final String FIELD_DESCRIPTION = "description";
     public static final String FIELD_EXPIRATION_DATE = "expirationDate";
     public static final String FIELD_COMMENTS = "comments";


     @Id
     @GeneratedValue
     private Long bankBranchId; //表ID，主键，供其他表做外键


     private Long bankId; //银行ID

     @NotEmpty
     @Length(max = 240)
     private String branchName; //分行名称

     @NotEmpty
     @Length(max = 80)
     private String branchType; //分行类型

     @NotEmpty
     @Length(max = 80)
     private String branchNo; //联行号

     @NotEmpty
     @Length(max = 240)
     private String swiftCode; //Swift code

     @NotEmpty
     @Length(max = 240)
     private String address; //地址

     @Length(max = 240)
     private String description; //说明

    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
     private Date expirationDate; //截止日期

     @Length(max = 240)
     private String comments; //备注


     public void setBankBranchId(Long bankBranchId){
         this.bankBranchId = bankBranchId;
     }

     public Long getBankBranchId(){
         return bankBranchId;
     }

     public void setBankId(Long bankId){
         this.bankId = bankId;
     }

     public Long getBankId(){
         return bankId;
     }

     public void setBranchName(String branchName){
         this.branchName = branchName;
     }

     public String getBranchName(){
         return branchName;
     }

     public void setBranchType(String branchType){
         this.branchType = branchType;
     }

     public String getBranchType(){
         return branchType;
     }

     public void setBranchNo(String branchNo){
         this.branchNo = branchNo;
     }

     public String getBranchNo(){
         return branchNo;
     }

     public void setSwiftCode(String swiftCode){
         this.swiftCode = swiftCode;
     }

     public String getSwiftCode(){
         return swiftCode;
     }

     public void setAddress(String address){
         this.address = address;
     }

     public String getAddress(){
         return address;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setExpirationDate(Date expirationDate){
         this.expirationDate = expirationDate;
     }

     public Date getExpirationDate(){
         return expirationDate;
     }

     public void setComments(String comments){
         this.comments = comments;
     }

     public String getComments(){
         return comments;
     }

     }
